### ISSUE TITLE
[BUG] Hardcoded colorTables file in DiscreteLegend

### ISSUE THREAD

**Issue by Vladimir-Kokin** [emerson-eps/color-tables#153]
`colorTables: colorTablesArray | string; `
was removed from _type colorLegendProps_ in react-app\src\component\Legend\DiscreteLegend.tsx
by PR #146
And now _colorTables_ in DiscreteLegend.tsx is just hardcoded 
`import colorTables from "../color-tables.json";`
and cannot be changed via prop.

Previously _type colorLegendProps_ had _colorTables_ but it was not used in
`export const DiscreteColorLegend: React.FC<colorLegendProps> = ({`
function parameters

So it seems _colorTables_ should be resored in _colorLegendProps_ and added to _DiscreteColorLegend_ parameters

**Comment by Vladimir-Kokin** [comment]
_colorTables_ also hardcoded in some another files such as
react-app\src\component\Utils\legendCommonFunction.ts 
react-app\src\component\ColorSelector\ColorSelectorWrapper.tsx 
in such form:
`import colorTables from "../../component/color-tables.json";`

**Comment by shruthirai** [comment]
Fixed
