### ISSUE TITLE
 `ColorSelector`: hover state and pointer cursor

### ISSUE THREAD

**Issue by rubenthoms** [emerson-eps/color-tables#252]
In order to improve the UX with `ColorSelector`, consider changing the cursor for the clickable elements to `pointer` and change the style for the hover state (e.g. slightly change the background color as it's done with the `Expand/Collapse` headers).

![image](https://user-images.githubusercontent.com/69145689/187153061-288c6105-cd66-4772-8b3f-30466f009d32.png)

**Comment by shruthirai** [comment]
@rubenthoms Thanks for the suggestion. Will make necessary changes as mentioned by you.

**Comment by shruthirai** [comment]
Done
