### ISSUE TITLE
color-tables.json is not imported correctly by index.ts

### ISSUE THREAD

**Issue by avipeter7** [emerson-eps/color-tables#259]
The import in index.ts is currently done by: 
import * as colorTables from "./component/color-tables.json";

So when colorTables is then exported, it is exported as a module instead of an array.
Then, when trying to import it from an outside project - it causes an error.

The correct import should be:
import { default as colorTables } from "./component/color-tables.json";

This way colorTables is an array, as it should be.

Another possible fix is to change the json file to a ts file that declares a colorTables array inside and exports it.

**Comment by shruthirai** [comment]
@avipeter7 I will have an look at this and will make necessary changes

**Comment by shruthirai** [comment]
@avipeter7 I have made the changes and pushed it. Can you please confirm if it works fine with the latest version ?

**Comment by shruthirai** [comment]
We verified from our end, hence closing.
