### ISSUE TITLE
Support "preview" possibility and standalone usage

### ISSUE THREAD

**Issue by anders-kiaer** [emerson-eps/color-tables#273]
We aim at replacing the current used color selector here: https://webviz-subsurface-example.azurewebsites.net/surface-with-seismic-cross-section with the Equinor + Emerson developed selector in this repository (in order to align and focus on one common component).

In order to do this we would like the following use case pattern to be supported:
1) Let the component show the current selected color scale 
![image](https://user-images.githubusercontent.com/31612826/190133706-05fe80fd-9a9b-4123-96ac-76b3ab1d83ff.png)
2) When color scale is clicked on, the dialog box pops up, i.e. what currently in the Emerson + Equinor component looks like: 
![image](https://user-images.githubusercontent.com/31612826/190133858-015f4ee0-411a-4493-b593-0e80e72e081a.png)

This usage pattern could e.g. also be added as an example in the storybook in this repo.

**Comment by anders-kiaer** [comment]
See also https://github.com/equinor/webviz-subsurface-components/issues/1196 for the larger "epic" issue based on discussion between @shruthirai, @rubenthoms et al.

**Comment by shruthirai** [comment]
@amroahmed90 should we close this issue now ?
