### ISSUE TITLE
Interpolation type is not correct upon re-render of the color selector.

### ISSUE THREAD

**Issue by amroahmed90** [emerson-eps/color-tables#362]
When you change the interpolation type (to nearest or logarithmic for example), close the color selector and then open it again, the interpolation type selected value falls back to "linear". However, the legend remains unchanged. 

As shown in the picture, the interpolation option is at "linear", yet the legend is at "nearest".

![image](https://user-images.githubusercontent.com/17360112/204225035-0879b34f-9b1c-4333-b88a-96cb88f6b498.png)

**Comment by amroahmed90** [comment]
Same behavior is noticed with the domain as well upon closing and reopening the color selector.

![image](https://user-images.githubusercontent.com/17360112/204228861-1d834a3a-3b2e-4492-9231-9f0c8eddf238.png)

**Comment by shruthirai** [comment]
Fixed
